name: CI/CD Pipeline - Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-image:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/backend-image:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: 54.167.199.97
          username: ubuntu
          key: ${{ secrets.DEVOPS_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/backend-image:latest
            docker stop backend-container || true
            docker rm backend-container || true
            docker run -d --name backend-container -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/backend-image:latest
